# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef8e39dfc899d4441249b518d1c6cf73076223438aa458d4ae0f02f0e998ad4ef117c87f85e4d1bb557d7bef92067920651583709c36f678063d99428ea3799f

test:
  secret_key_base: 319652f45e324b66db04ec1b8fbcd88c00082dadbf3e783abbde1760caeed2e7c580bb63f2b2de01e0a7ce390924b9e3e2093c6565df2f1b68610b5c113c7ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
